application:
  port: 8000
database:
  hose: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: localhost
  sender_email: test@gmail.com
  authorization_token: "my-secret-token" #for production, nothing has been set yet
  timeout_milliseconds: 10000